name: buil

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  semgrep:
    name: semgrep
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
    - name: Fetch
      uses: actions/checkout@v3
    - name: Semgrep
      run: semgrep ci --config=auto --sarif --output=semgrep.sarif || true
    - name: upload_output
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: semgrep.sarif
      if: always()
      
      

      
